name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1

      - name: Install tools
        run: go run scripts/build.go install-tools

      - name: Run unit tests
        run: go run scripts/build.go test

      - name: Security scan
        run: |
          govulncheck ./...
          gosec -quiet ./...

      - name: Run integration tests
        run: go run scripts/build.go test --int

      - name: Build binary
        run: go run scripts/build.go build
